### PR TITLE
Allow linking to particular result page in contact browser

### PR DESCRIPTION
**Pull request by simozhan**
JIRA: PDC-1291

This implementation only put the request data into the URL and allow easy sharing of the results.
Back/Forward functionality is not available. Maybe that needs more effort on caching data.

Faked URL is used to test in local environment. When the application is deployed to real server, it will be commented out.

### CODE REVIEW

**Comment by lubomir** [comment]
I don't understand how this should work, and it does not work for me.

My initial idea would be that the request parameters would be serialized into the url hash (`#page=1&….`). On initial load the app would check these params and optionally load the data from server. Something like [this](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/apps/common/templates/browsable_api/api.html#L71-L81).

**Comment by simozhan** [comment]
@lubomir Thanks for your guide. I am trying it.
This implementation is part of the original ticket. My idea is using window.history.PushState to put URL in browser and using window.onpopstate to reload the previous form(this part is lacking). So currently, you can just see the url is put in browser and Back/Forward is available as well. If you want to test it, you can deploy pdc-contact-browser in local as a webapp and change the faked url to have the same origin with pdc-contact-browser.

**Comment by simozhan** [comment]
@lubomir @ycheng-aa @bliuredhat please help to review. thanks

**Comment by lubomir** [comment]
I like this. It seems to work fine for sending links and then restoring the context. :+1:  To get it working locally, I also needed to `npm install history`, but this could be something broken in my local installation.

**Comment by ycheng-aa** [comment]
:+1:

**Comment by bliuredhat** [comment]
:+1:

**Pull request merged**
