### PR TITLE
Create a UI for viewing contacts.

### PR DESCRIPTION
**Pull request by simozhan**
1. Component only support exact words to match.
2. All in release column means all releases, not include global component.
3. For global component, the release column in Result shows N/A.
4. Server and token are set in a json file.

JIRA: PDC-1150

### CODE REVIEW

**Comment by bliuredhat** [comment]
:+1:

**Comment by xychu** [comment]
Looks good to me.

**Comment by ycheng-aa** [comment]
Looks good for me.

I don't have too much front-end knowledge. The effect looks good for me. Maybe how could let user customize settings need to be thought about before packaging.

**Comment by simozhan** [comment]
@ycheng-aa yes. the issue will be considered before packaging.

**Comment by simozhan** [comment]
Let's merge it and see if any feedback from customer first.

**Pull request merged**
