### PR TITLE
Get Rest Api Url dynamically.

### PR DESCRIPTION
**Pull request by simozhan**
PDC-1398

### CODE REVIEW

**Comment by lubomir** [comment]
I think this would work, but it puts a requirement on how the UI can be deployed: it must be on the same server in a specific location. It probably is not a big problem.

My original proposal was to keep the server settings file, but instead of including it in the bundle, just download it the same way token is obtained and releases loaded when the client is displayed for the first time.

**Comment by simozhan** [comment]
Thanks @lubomir . You are right, the UI's server url is not configurable. i changed it in the new patch. please check if it is ok.

**Comment by lubomir** [comment]
This looks good to me.

I think it could be simplified by using jquery to do the request, but it's not necessary. The only reason why the token obtaining is using raw `XMLHttpRequest` is that I could not find documentation on how jquery works with kerberos auth.

**Comment by simozhan** [comment]
Thanks @lubomir . Fixed.

**Comment by bliuredhat** [comment]
looks good for me

**Comment by lubomir** [comment]
:+1:

**Pull request merged**
