### PR TITLE
Fix filtering only some fields

### PR DESCRIPTION
**Pull request by lubomir**
Current PDC server reports an error when it sees invalid field, and separating fields with commas is not supported. Instead they should be sent as separate keys. We need a custom serializer function to avoid
creating `fields[]=foo&fields[]=b` which is what JQuery does by default.

### CODE REVIEW

**Comment by hluk** [comment]
Second argument in `$.param()` can help.
```js
traditional = true
$.param({fields: ['email', 'mail_name']}, traditional)
// fields=email&fields=mail_name
```

**Comment by lubomir** [comment]
Oh yes, that is much better.

**Comment by hluk** [comment]
Do we still want to merge this even though we'll fix it on PDC side? Using the "traditional" parameter serialization could be useful in future.

**Comment by lubomir** [comment]
I think it might be useful (and maybe it's more obvious that there are two fields required), but with a fix on the server it there's no rush to get it released.

**Review by hluk — APPROVED** [review]

**Pull request merged**
