### PR TITLE
No server setting file and get all releases and contact types at start

### PR DESCRIPTION
**Pull request by simozhan**
Change this in a simple way as the draft version. Maybe there is already good "wheel" in React.

### CODE REVIEW

**Comment by bliuredhat** [comment]
:+1:

**Comment by ycheng-aa** [comment]
:+1:

**Comment by lubomir** [comment]
This solution for displaying the releases works, but I feel just getting all releases would be a better solution – less code and easier to use. The only drawback would be longer wait at the start. Just disabling paging for this request would probably do it.

**Comment by simozhan** [comment]
Thanks @lubomir . Actually just because of the longer wait, i gave up to get all releases. That is based on the qa-dt server, there are many faked releases. I will change it back, if there is performance issue in the product server, i will think about if there is better way or using this implementation.

**Comment by ycheng-aa** [comment]
Looks good.

**Comment by bliuredhat** [comment]
:+1:

**Pull request merged**
